#端口号
server:
  port: 8181

spring:
  #mysql 配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/ms-notify?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #配置redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: root123456
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000

  #配置mail
  mail:
    #邮件协议smtp
    host: smtp.qq.com
    #发送者的邮件的用户名
    username: 1608550717@qq.com
    #使用的编码
    default-encoding: utf-8
    #移动端客户授权码
    password: cctitlbsnklffjhd
    port: 465
    test-connection: true
    properties.mail.smtp.ssl.enable: true
#    debugger: true
#    smtp:
#     timeout: 1000
#     socketFactory:
#       port: 465


#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wl.msnotify.entity

#pageHelper 分页插件
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true



