#端口号
server:
  port: 8181

#mysql 配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms-notify?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    #邮件协议smtp
    host: smtp.qq.com
    #发送者的邮件的用户名
    username: 1608550717@qq.com
    #使用的编码
    default-encoding: utf-8
    #移动端客户授权码
    password: cctitlbsnklffjhd
    port: 465
    properties.mail.smtp.ssl.enable: true

#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wl.msnotify.entity

#pageHelper 分页插件
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true



