#端口号
server:
  port: 8181
#任务调度
quartz:
  enabled: true

spring:
  #mysql 配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/ms-notify?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #配置redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: root123456
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000

#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wl.msnotify.entity

#pageHelper 分页插件
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true



